"""Generate ``report.md`` from the human data and every condition in ``outputs/``."""

from __future__ import annotations

import json
import math
from collections import Counter
from datetime import date

from analysis import Z
from gate import CHECKS
from study import ARMS, BY_SEGMENT, HERE, LABEL_NOTE, OUT, PUBLISHED

ORDER = ("mock", "isolated-mock", "claude", "isolated-claude")
DESCRIBE = {
    "mock": "mock respondent, full instrument context (history + page)",
    "isolated-mock": "same mock, each question asked in isolation (no history, no page)",
    "claude": "Claude, full instrument context",
    "isolated-claude": "Claude, questions in isolation",
}


def human_consistency(rows: list[dict[str, str]]) -> dict:
    """Recorded assignment in the human export: does Segment agree with the randomizer's
    display-order columns and with `target`? (Exposure itself is not observable for
    humans: the export has no column for a text-only screen.)"""
    c: Counter = Counter()
    for r in rows:
        arm = BY_SEGMENT.get(r.get("Segment", ""))
        if arm is None:
            c["no_segment"] += 1
            continue
        c[arm.key] += 1
        if r.get(f"FL_491_DO_{arm.key}") != "1" or any(
            r.get(f"FL_491_DO_{k}") for k in ARMS if k != arm.key):
            c["do_mismatch"] += 1
        if r.get("target") != arm.target:
            c["target_mismatch"] += 1
    return dict(c)


def _f(x: float | None, nd: int = 2, sign: bool = False) -> str:
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "n/a"
    return f"{x:+.{nd}f}" if sign else f"{x:.{nd}f}"


def _se(c: dict) -> float:
    return (c["diff_hi"] - c["diff_lo"]) / (2 * Z)


def write(pre: dict, human: dict) -> object:
    conds = {m: json.loads((OUT / m / "results.json").read_text())
             for m in ORDER if (OUT / m / "results.json").exists()}
    hc = human["contrast"]
    L: list[str] = []
    a = L.append
    a("# Targeting Fairness: end-to-end study report")
    a("")
    a(f"_Generated by `studies/targeting_fairness/run.py` on {date.today().isoformat()}. "
      "Do not edit by hand._")
    a("")
    a("**Study.** Twin-2K-500 mega-study replication *Segmentation fairness: gender, taste* "
      "(`survey.qsf`). One between-subjects factor, randomizer `FL_491` (1 of 2, evenly "
      "presented), sets `Segment`; display logic on `Segment` then shows one of two text "
      "vignettes on the same page as the outcome, `fair1` (\"How fair is this advertising "
      "plan?\", 1 = not at all fair, 9 = very fair).")
    a("")
    a("| arm | records `Segment` | records `target` | vignette displayed | label used here |")
    a("|---|---|---|---|---|")
    for arm in ARMS.values():
        a(f"| `{arm.key}` | {arm.segment} | {arm.target} | `{arm.screen}`: \"...{arm.phrase}\" "
          f"| **{arm.label}** |")
    a("")
    a("The contrast everywhere below is **mean(fair1 | broad shown) − mean(fair1 | targeted "
      "shown)**, defined by what was displayed.")
    a("")
    a(f"> **Labelling note.** {LABEL_NOTE}")
    a("")

    # ---------------------------------------------------------------- 1 execution
    a("## 1. Execution status")
    a("")
    a(f"- **Preflight** (`surveyir check --strict`, saved in `outputs/check.txt`): "
      f"{len(pre['blocking'])} blocking gaps"
      + (": " + "; ".join(pre["blocking"]) if pre["blocking"] else
         "; the instrument runs under strict execution with no `allow` or `implementations`."))
    a(f"- **Design** (`outputs/design.txt`): `FL_491` is reported as an "
      f"*{pre['factor_contrast']}* contrast. Its arms only set embedded data; the exposure is "
      "decided afterwards by display logic, so the gate checks the displayed screens directly.")
    a("")
    if conds:
        a("Exposure gate, per simulated condition (failures out of n respondents):")
        a("")
        a("| check | " + " | ".join(conds) + " |")
        a("|---|" + "---|" * len(conds))
        a("| respondents (arms) | " + " | ".join(
            f"{c['gate']['n']} ({', '.join(f'{k}: {v}' for k, v in c['gate']['arms'].items())})"
            for c in conds.values()) + " |")
        for k, desc in CHECKS.items():
            a(f"| {desc} | " + " | ".join(
                str(c["gate"]["checks"][k]["failures"]) for c in conds.values()) + " |")
        a("| strict-mode `ExecutionError`s | " + " | ".join(
            str(len(c["gate"]["errors"])) for c in conds.values()) + " |")
        a("| approximations recorded (any kind) | " + " | ".join(
            (", ".join(f"{k} ×{v}" for k, v in c["gate"]["approximations"].items()) or "none")
            for c in conds.values()) + " |")
        a("| **gate** | " + " | ".join(
            "**PASSED**" if c["gate"]["passed"] else "**FAILED**" for c in conds.values()) + " |")
        a("")
        nc = pre.get("negative_controls")
        if nc:
            sw, lg = nc["swapped_design"], nc["legacy_answerer"]
            a("Negative controls (the gate must be able to fail; "
              "`outputs/negative_controls.json`): checked against a deliberately swapped "
              "design statement, the mock runs fail "
              f"the gate ({'FAILED' if not sw['passed'] else 'unexpectedly PASSED'}: "
              + ", ".join(f"{k} ×{v}" for k, v in sw["failed_checks"].items())
              + f" of {sw['n']}); a legacy `(view, state)` answerer that can read hidden "
              f"state fails it too ({'FAILED' if not lg['passed'] else 'unexpectedly PASSED'}: "
              + ", ".join(f"{k} ×{v}" for k, v in lg["failed_checks"].items())
              + f" of {lg['n']}).")
            a("")
        a("Information state at the outcome (not part of the gate; it describes what the "
          "respondent *model* received, which the isolated baseline removes on purpose):")
        a("")
        a("| condition | own vignette in model context | other arm's vignette in context |")
        a("|---|---|---|")
        for m, c in conds.items():
            i = c["information_state"]
            a(f"| {m} | {_f(100 * i['own_vignette_in_context'], 0)}% | "
              f"{_f(100 * i['other_vignette_in_context'], 0)}% |")
        a("")
        a("Example traces per arm are in `outputs/<condition>/traces/`: the respondent-visible "
          "transcript, the `exposures()` record with the audit's randomizer decision, and the "
          "exact text the model could read when it rated `fair1`.")
        a("")
    cons = human["consistency"]
    a(f"- **Human data** (n = {sum(v for k, v in cons.items() if k in ARMS)}): exposure is not "
      "observable (the export has no column for a text-only screen), so it is inferred from "
      "the instrument's display logic. The recorded assignment is internally consistent: "
      f"`Segment` disagrees with `FL_491_DO_*` in {cons.get('do_mismatch', 0)} rows and with "
      f"the arm's `target` value in {cons.get('target_mismatch', 0)} rows.")
    a("")

    # ---------------------------------------------------------------- 2 contrast
    a("## 2. Treatment contrast (primary)")
    a("")
    a("Difference in means with a Welch 95% CI; Cohen's d (pooled SD, as the original "
      "analysis) with a large-sample 95% CI. Normal critical values (n > 150 per arm).")
    a("")
    a("| source | n broad / targeted | mean broad | mean targeted | broad − targeted [95% CI] "
      "| d [95% CI] |")
    a("|---|---|---|---|---|---|")

    def row(name: str, c: dict) -> None:
        if "diff" not in c:
            a(f"| {name} | {c.get('n_broad', 0)} / {c.get('n_targeted', 0)} | n/a | n/a | n/a "
              "| n/a |")
            return
        a(f"| {name} | {c['n_broad']} / {c['n_targeted']} | {_f(c['mean_broad'])} | "
          f"{_f(c['mean_targeted'])} | {_f(c['diff'], sign=True)} [{_f(c['diff_lo'], sign=True)}"
          f", {_f(c['diff_hi'], sign=True)}] | {_f(c['d'], sign=True)} [{_f(c['d_lo'], sign=True)}"
          f", {_f(c['d_hi'], sign=True)}] |")

    row("**human**", hc)
    for m, c in conds.items():
        row(f"{m} ({DESCRIBE[m]})", c["contrast"])
    a("")
    a("**Original analysis, as written.** The mega-study script reports Cohen's d as "
      "(first `Segment` level in file order) − (second), so its sign depends on row order. "
      "The port in `analysis.py` reproduces it; where the mega-study checkout and its "
      "virtualenv are present the unmodified script is also run on the same files.")
    a("")
    a("| data | ported original d | original script d | published d |")
    a("|---|---|---|---|")
    first = next(iter(conds.values()), None)
    orig_h = (first or {}).get("original_script") or {}
    a(f"| human | {_f(human['original_d'], 4, True)} | "
      f"{_f(orig_h.get('effect_size_human'), 4, True)} | "
      f"{_f(PUBLISHED['effect_size_human'], 4, True)} |")
    for m, c in conds.items():
        o = c.get("original_script") or {}
        a(f"| {m} | {_f(c['original_d'], 4, True)} | {_f(o.get('effect_size_twin'), 4, True)} "
          "| |")
    a(f"| mega-study LLM twins (reference; not run here) | | | "
      f"{_f(PUBLISHED['effect_size_twin'], 4, True)} |")
    a("")
    if orig_h and "error" in orig_h:
        a(f"The original script failed: `{orig_h['error'][-300:]}`")
        a("")
    first = BY_SEGMENT.get(human["first_segment"])
    a(f"The human file's first row has `Segment` = {human['first_segment']} "
      f"({first.label if first else 'unknown'} shown), so the original d is "
      f"{first.label if first else '?'} − other: the published value is "
      f"{'negative' if PUBLISHED['effect_size_human'] < 0 else 'positive'} for that reason, "
      "and its magnitude matches the oriented contrast above. Simulated files take their row "
      "order from the human file (merge on `TWIN_ID`), but their arms are drawn "
      "independently, so the original sign for a simulated condition is set by whichever "
      "arm its first simulated respondent drew. For the mega-study's own LLM twins the "
      "published d cannot be oriented from the summary file alone.")
    a("")

    # ---------------------------------------------------------------- 3 marginals
    a("## 3. Marginals (secondary)")
    a("")
    a("| source | n | mean | sd | " + " | ".join(str(k) for k in range(1, 10)) + " |")
    a("|---|---|---|---|" + "---|" * 9)
    for name, mg in [("human", human["marginal"])] + [(m, c["marginal"]) for m, c in conds.items()]:
        n = mg["n"] or 1
        a(f"| {name} | {mg['n']} | {_f(mg['mean'])} | {_f(mg['sd'])} | " + " | ".join(
            f"{100 * mg['counts'][str(k)] / n:.0f}%" for k in range(1, 10)) + " |")
    a("")
    a("Marginals can match while contrasts differ (and vice versa); the contrast is the "
      "estimand of the experiment.")
    a("")

    # ---------------------------------------------------------------- 4 separation
    a("## 4. Execution failures vs predictive discrepancies")
    a("")
    failed = {m: c for m, c in conds.items() if not c["gate"]["passed"]}
    a("**Execution failures** (the instrument was not administered as specified; evidence: "
      "strict mode, the audit and the traces):")
    a("")
    if not conds:
        a("- no simulated condition has been run.")
    elif not failed:
        a(f"- none. All {len(conds)} conditions passed every gate check, with no strict-mode "
          "errors and no unallowed approximations. Differences from the human estimates below "
          "are therefore about the respondent model, not the administration.")
    else:
        for m, c in failed.items():
            bad = [k for k, v in c["gate"]["checks"].items() if v["failures"]]
            a(f"- **{m}**: failed {', '.join(bad) or 'strict execution'}; "
              f"{len(c['gate']['errors'])} ExecutionErrors. Its estimates are not comparable "
              "with the human ones until this is fixed.")
    a("")
    a("**Predictive discrepancies** (administered correctly, answers differ from humans): "
      "simulated minus human contrast, with a 95% CI from independent samples.")
    a("")
    a("| condition | simulated − human (points) [95% CI] | d: simulated − human | verdict |")
    a("|---|---|---|---|")
    for m, c in conds.items():
        sc = c["contrast"]
        if "diff" not in sc or m in failed:
            a(f"| {m} | n/a | n/a | not comparable (execution failure) |")
            continue
        gap = sc["diff"] - hc["diff"]
        se = math.hypot(_se(sc), _se(hc))
        lo, hi = gap - Z * se, gap + Z * se
        verdict = "consistent with human" if lo <= 0 <= hi else "differs from human"
        a(f"| {m} | {_f(gap, sign=True)} [{_f(lo, sign=True)}, {_f(hi, sign=True)}] | "
          f"{_f(sc['d'] - hc['d'], sign=True)} | {verdict} |")
    a("")
    a("For the mock conditions these discrepancies are expected and uninformative about any "
      "real model: the mock's effect is planted, not predicted.")
    a("")

    # ---------------------------------------------------------------- 5 planted
    mocks = {m: c for m, c in conds.items() if m.endswith("mock")}
    if mocks:
        a("## 5. Planted-effect check (mock)")
        a("")
        planted = next(c["planted_effect"] for c in mocks.values())
        a(f"The mock adds ±{planted / 2:g} to a seeded 3–7 rating according to which vignette "
          f"text it can read, so the planted contrast is **{planted:+g}** when the instrument's "
          "context reaches the model and **0** when it doesn't. Both conditions use the same "
          "simulator seed, so assignments and traces are identical; only the model's context "
          "differs.")
        a("")
        a("| condition | estimate [95% CI] | recovers planted effect? | CI excludes 0? |")
        a("|---|---|---|---|")
        for m, c in mocks.items():
            sc = c["contrast"]
            if "diff" not in sc:
                continue
            covers = sc["diff_lo"] <= planted <= sc["diff_hi"]
            excl = not (sc["diff_lo"] <= 0 <= sc["diff_hi"])
            a(f"| {m} | {_f(sc['diff'], sign=True)} [{_f(sc['diff_lo'], sign=True)}, "
              f"{_f(sc['diff_hi'], sign=True)}] | {'yes' if covers else 'no'} | "
              f"{'yes' if excl else 'no'} |")
        a("")
        if "mock" in mocks and "isolated-mock" in mocks:
            m1, m0 = mocks["mock"]["contrast"], mocks["isolated-mock"]["contrast"]
            if "diff" in m1 and "diff" in m0:
                a(f"With the instrument preserved, the pipeline recovers the planted effect "
                  f"({_f(m1['diff'], sign=True)}). The isolated baseline, the *same* model "
                  f"asked `fair1` without the vignette, estimates {_f(m0['diff'], sign=True)}: "
                  "it cannot respond to a treatment it never sees, so a context-free pipeline "
                  "reports a null effect even for a respondent model whose behaviour depends "
                  "entirely on the treatment. Its execution gate still passes, because the "
                  "*instrument* was administered correctly; the information-state table in "
                  "section 1 is what exposes the difference. This is why the treatment screens, "
                  "and not only the outcome questions, must reach the respondent model.")
                a("")

    # ---------------------------------------------------------------- 6 cost
    a("## 6. Gated LLM run: cost estimate")
    a("")
    est = next((c["llm_cost_if_run"] for m, c in conds.items() if m == "mock"), None)
    iso = next((c["llm_cost_if_run"] for m, c in conds.items() if m == "isolated-mock"), None)
    if est:
        p = est["assumptions"]["price_usd_per_mtok"]
        a("Not run. The prompts `examples/llm_respondents.ClaudeRespondent` would send were "
          "measured on the mock runs (system prompt + conversation built from `ctx.history` "
          "+ JSON schema, per question it answers), converted at "
          f"{est['assumptions']['chars_per_token']:g} characters per token, with "
          f"{est['assumptions']['output_tokens_per_request']} output tokens per answer and "
          f"**ASSUMED** prices of ${p['input']:g} / ${p['output']:g} per million input / output "
          f"tokens for `{est['model']}` (not looked up; replace before approving).")
        a("")
        a("| condition | respondents | requests | input tokens | output tokens | est. USD |")
        a("|---|---|---|---|---|---|")
        for name, e in (("claude", est), ("isolated-claude", iso)):
            if e:
                a(f"| {name} | {e['respondents']} | {e['requests']} | {e['input_tokens']:,} | "
                  f"{e['output_tokens']:,} | ${e['usd']:.2f} |")
        a("")
    a("Run only with explicit approval: `uv run --with anthropic python "
      "studies/targeting_fairness/run.py --model claude --i-approve-spend` (see "
      "`studies/README.md`).")
    a("")
    path = HERE / "report.md"
    path.write_text("\n".join(L))
    return path

