"""What this study is: the instrument, its arms, its outcome and where the human data lives.

Everything here is written from the instrument (``survey.qsf``), not generated by
surveyir, so the exposure gate checks the simulator against an independent
statement of what each arm should show.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
QSF = HERE / "survey.qsf"
OUT = HERE / "outputs"

#: Twin-2K-500 mega-study checkout (for the original analysis script and its venv).
MEGA_STUDY = Path(
    os.environ.get("TWIN_MEGA_STUDY", Path.home() / "Code" / "Twin-2K-500-Mega-Study")
).expanduser()


def human_csv() -> Path:
    """The human Qualtrics export. Not redistributed: set ``SURVEYIR_TWIN_DAT`` to the
    mega-study's ``.dat`` directory (the same variable surveyir's validation tests use)."""
    dat = os.environ.get("SURVEYIR_TWIN_DAT")
    root = Path(dat).expanduser() if dat else MEGA_STUDY / ".dat"
    path = root / "targeting_fairness" / "raw_data" / "response.csv"
    if not path.exists():
        raise SystemExit(
            f"human responses not found at {path}; set SURVEYIR_TWIN_DAT to the "
            "Twin-2K-500-Mega-Study .dat directory"
        )
    return path


@dataclass(frozen=True)
class Arm:
    key: str  # flow id of the randomizer arm (FL_491_DO_<key> in the export)
    label: str  # what the respondent is actually shown
    screen: str  # the treatment screen this arm must display
    phrase: str  # text unique to that screen
    segment: str  # value the arm records in `Segment`
    target: str  # value the arm records in `target` (see LABEL_NOTE)


FACTOR = "FL_491"
OUTCOME = "QID1396"  # export tag fair1: "How fair is this advertising plan?" 1..9
OUTCOME_COLUMN = "fair1"
OUTCOME_RANGE = (1, 9)
END_NODE = "FL_421"  # the End of Survey element at the end of the flow

#: Read from the flow (FL_493 / FL_497 set Segment) and the display logic of QID1459
#: (Segment = 2) and QID1460 (Segment = 1).
ARMS = {
    "FL_493": Arm(
        key="FL_493",
        label="targeted",
        screen="QID1459",
        phrase="advertise the snacks to women directly",
        segment="2",
        target="broad",
    ),
    "FL_497": Arm(
        key="FL_497",
        label="broad",
        screen="QID1460",
        phrase="advertise the snacks broadly to the general public",
        segment="1",
        target="female",
    ),
}
#: The contrast reported everywhere: mean(fair1 | broad shown) - mean(fair1 | targeted shown).
TREATED, CONTROL = "FL_497", "FL_493"
BY_SEGMENT = {a.segment: a for a in ARMS.values()}

LABEL_NOTE = (
    "The embedded field `target` is the reverse of what each arm displays: the arm that "
    "records target='broad' (Segment=2) shows the vignette in which the company advertises "
    "'to women directly', and the arm that records target='female' (Segment=1) shows the "
    "'broadly to the general public' vignette. The original analysis conditions on "
    "`Segment` and does not use `target`, so its estimate is unaffected, but anyone who "
    "labels arms by `target` would reverse the sign of the effect. This is an instrument "
    "labelling issue read off the exposure traces, not an execution failure."
)

#: Panel fields the flow declares (FL_496); simulated respondents get synthetic values.
PANEL_FIELDS = ("PROLIFIC_PID", "STUDY_ID", "SESSION_ID")

#: Published original-pipeline estimates for this study, from the mega-study's
#: ``mega_study_evaluation/targeting_fairness/test/Targeting fairness default persona
#: meta analysis.csv`` (Cohen's d, sign set by row order; see analysis.py).
PUBLISHED = {"effect_size_human": -0.5436183045997864, "effect_size_twin": -1.0232099501617782}
